source 'https://rubygems.org'

gem 'sinatra'
gem 'redcarpet'
gem 'rouge'
gem 'json'
gem 'net-http', require: 'net/http'
gem 'uri'
gem 'sequel'
gem 'bcrypt'
gem 'erb'
gem 'cgi'
gem 'fileutils'
gem 'zip'
gem 'mime-types', require: 'mime/types'
gem 'readingtime'
gem 'sinatra-contrib', require: ['sinatra/reloader']
gem 'sqlite3'
gem "rackup", "~> 2.1"
gem 'dotenv'
